### ISSUE TITLE
1.3.0 release checklist

### ISSUE THREAD

**Issue by polsys** [polsys/ennemi#111]
This is a meta-issue tracking the things that should be done before the release.

### At the start of development cycle
- [x] Update the version number
- [x] Set a target date for the release
- [x] Review and fix Sonar issues
- [x] Upgrade Github Actions step versions

### Release
- [x] Merge the documentation branch
- [x] Publish a release, verify that PyPI push succeeds
- [x] Update the release notes with the Zenodo DOI
- [x] Check the Zenodo metadata, update description if necessary

Draft release notes: https://gist.github.com/polsys/f0757723b73194a0bccb9043e7c75e47
