### ISSUE TITLE
Add more unit test cases

### ISSUE THREAD

**Issue by polsys** [polsys/ennemi#20]
- [ ] ~To get the code coverage to 100%, there must be a test of conditional MI with `k=N`.~
  - Driver requires `k<N`, I don't want to introduce special code for this test only.
- [x] There is not yet a driver test of conditional MI with multidimensional condition. (#42)
- [x] More distributions with analytically known MI, see Darbellay & Vajda (DOI: 10.1109/18.825848) and Kraskov et al. (DOI: 10.1103/PhysRevE.69.066138) (#42)
- [x] The "too large `k` after mask" test does not take lags into account. (#38)
- [x] Other corner cases with confusing error messages? (#38)
