### ISSUE TITLE
Beta 1 development cycle

### ISSUE THREAD

**Issue by polsys** [polsys/ennemi#41]
This is a meta-issue tracking the things that should be done before the release.

### At the start of development cycle
- [x] Update the version number, set development status to `Beta` in PyPI metadata
- [ ] Rename `master` branch to `main`, fix references in CI, Sonar and docs
  - Apparently this change would break GitHub Pages, so deferring this for now
  - I'd still want to change this; both for inclusivity and because the "17 commits to master since this release" message is confusing to non-technical users
- [x] Set a target date for the release
- [x] Add a `py.typed` file so that our annotations are visible to users (https://mypy.readthedocs.io/en/stable/installed_packages.html)
- [x] Replace `#type:ignore` comments by a mypy configuration file

### Release
- [x] Fix Sonar issues
- [x] Add a CI step to check the package build
- [x] Mention the beta status in docs (index, README, DESCRIPTION)
- [x] Mention "and contributors" in LICENSE and Zenodo
- [x] Add email address to README
- [x] Merge the documentation branch
- [x] Review docs, remove warning about beta1 being still unreleased
- [x] Consider simplifying the acronym to "Easy nearest neighbor [...]"
- [x] Mention `@morrme` in release notes
- [x] Publish a release, verify that PyPI push succeeds
- [x] Update the release notes with the Zenodo DOI
- [x] Check the Zenodo metadata, update description if necessary
- [x] Set new baseline for Sonar

Draft release notes: https://gist.github.com/polsys/f0757723b73194a0bccb9043e7c75e47
