### ISSUE TITLE
1.0.0 development cycle

### ISSUE THREAD

**Issue by polsys** [polsys/ennemi#74]
This is a meta-issue tracking the things that should be done before the release.

### At the start of development cycle
- [x] Update the version number, set development status to `Stable` in PyPI metadata
- [x] Set a target date for the release
- [ ] Track the `master->main` migration tool of GitHub (need to update references in CI and docs as well)

### Release
- [ ] Address any review comments from the journal
- [x] Review and fix remaining Sonar issues
- [x] Mention the stable status in docs (index, README, DESCRIPTION)
- [x] Link to release notes / `Watch releases` in README
- [ ] Copy-edit the README more
- [ ] Merge the documentation branch, if applicable
- [x] Publish a release, verify that PyPI push succeeds
- [x] Update the release notes with the Zenodo DOI
- [x] Check the Zenodo metadata, update description if necessary
- [ ] Mention funding in Zenodo metadata?
- [ ] Set new baseline for Sonar

Draft release notes: https://gist.github.com/polsys/f0757723b73194a0bccb9043e7c75e47
