### ISSUE TITLE
1.1.0 development cycle

### ISSUE THREAD

**Issue by polsys** [polsys/ennemi#83]
This is a meta-issue tracking the things that should be done before the release.

### At the start of development cycle
- [x] Update the version number
- [x] Set a target date for the release
- [ ] Track the `master->main` migration tool of GitHub (need to update references in CI and docs as well)

### Release
- [x] Review and fix Sonar issues
- [x] Merge the documentation branch
- [x] Publish a release, verify that PyPI push succeeds
- [x] Update the release notes with the Zenodo DOI
- [x] Check the Zenodo metadata, update description if necessary
- [ ] Set new baseline for Sonar

Draft release notes: https://gist.github.com/polsys/f0757723b73194a0bccb9043e7c75e47
